language: node_js
node_js: "6"

before_script:
- (cd test_app; mkdir -p node_modules/.bin)
- (cd test_app/node_modules; ln -s ../.. binwrap)
- (cd test_app/node_modules/.bin; ln -s ../binwrap/bin/binwrap-install)
- (cd test_app/node_modules/.bin; ln -s ../binwrap/bin/binwrap-test)
