environment:
  matrix:
  - nodejs_version: "10"
  - nodejs_version: "6"

matrix:
  fast_finish: true

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:Platform
  - node --version
  - npm --version
  - cd test_app
  - npm install ../

test_script:
  - npm test
